swagger: '2.0'
info:
  title: Babu Gopal
  description: ''
  version: '1.0'
host: elastic.snaplogic.com:443
basePath: /api/1/rest/slsched/feed/Partners/Cognizant/Babu Gopal
schemes:
- https
paths:
  /BG-READ-ENCRYPTED-FILE-Task:
    post:
      consumes:
      - application/json
      produces: []
      responses:
        '200':
          description: OK
securityDefinitions:
  basicAuth:
    type: basic
security:
- basicAuth: []
